name: check github actions

on:
  workflow_call:

jobs:
  lint_workflows:
    name: lint workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Lint GitHub Actions workflow files
        uses: raven-actions/actionlint@01fce4f43a270a612932cb1c64d40505a029f821
        with:
          group-result: false
