name: check markdown

on:
  workflow_call:
    inputs:
      files:
        type: string
        default: "**/*.md"
      prettier_version:
        type: string
        default: "latest"

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Check Markdown file formatting
        run: npx --yes "prettier@${{ inputs.prettier_version }}" --check --debug-check --color --prose-wrap always -- ${{ inputs.files }}
