name: check rust / miri

on:
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings

jobs:
  test_miri:
    name: test miri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install nightly Rust toolchain
        uses: dtolnay/rust-toolchain@315e265cd78dad1e1dcf3a5074f6d6c47029d5aa
        with:
          toolchain: nightly
          components: miri
      - name: Set override to nightly Rust
        run: rustup override set nightly
      - name: Setup Miri environment
        run: cargo miri setup
      - name: Compile tests with Miri
        run: cargo miri test --no-run
      - name: Run tests with Miri
        run: cargo miri test
