name: deploy github pages / rust

on:
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings

jobs:
  build_docs:
    name: build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install nightly Rust toolchain
        uses: dtolnay/rust-toolchain@315e265cd78dad1e1dcf3a5074f6d6c47029d5aa
        with:
          toolchain: nightly
      - name: Build docs
        env:
          RUSTDOCFLAGS: --enable-index-page -Z unstable-options
        run: cargo +nightly doc --no-deps
      # prevent deployment_perms_error due to file permissions
      - name: Remove lock file
        run: rm target/doc/.lock
      - name: Upload github-pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
        with:
          path: target/doc

  deploy_docs_artifact:
    name: deploy docs artifact
    permissions:
      actions: read
      id-token: write
      pages: write
    needs: build_docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
