name: publish crate

on:
  workflow_call:
    secrets:
      CARGO_REGISTRY_TOKEN:
        description: crates.io API Token
        required: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings

jobs:
  publish_unpublished:
    name: publish unpublished
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@315e265cd78dad1e1dcf3a5074f6d6c47029d5aa
        with:
          toolchain: stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab
        with:
          shared-key: stable-ubuntu-latest
        timeout-minutes: 5

      - name: Install cargo-release
        uses: taiki-e/install-action@5d427d86f088a6cedcddb92b3ad038d30721b52f
        with:
          tool: cargo-release

      - name: Publish crate to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo release publish -v --execute --no-confirm --allow-branch="HEAD"

      - name: Annotate workflow run with published crate URL
        run: |-
          echo "### :shipit: Published crate for ${GITHUB_REF_NAME}:" >>"$GITHUB_STEP_SUMMARY"
          echo "- https://crates.io/crates/${GITHUB_REF_NAME%-v*}/${GITHUB_REF_NAME#*-v}/" >>"$GITHUB_STEP_SUMMARY"
